# Generated by Django 2.2.7 on 2019-11-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base_fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(null=True)),
                ('is_visited', models.BooleanField(null=True)),
                ('is_rediagnose', models.BooleanField(null=True)),
                ('medicine', models.TextField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MedicalDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('department', models.ManyToManyField(to='core.MedicalDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Symtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TextField()),
                ('degree', models.IntegerField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Disease')),
                ('self_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SelfDiagnosis')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='department',
            field=models.ManyToManyField(to='core.MedicalDepartment'),
        ),
    ]
