# Generated by Django 2.2.7 on 2019-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdiagnosis',
            name='avg_price',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
    ]
